---
- name: Add Galera configuration
  template: src=etc/my.cnf.j2 
            dest=/etc/my.cnf
            owner=root 
            group=root 
            mode=0644
  notify: Restart MySQL Galera cluster